name: Deploy Vue SPA to S3
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  VITE_API_URL: ${{ vars.VITE_API_URL }}
  VITE_PMTILES_URL: ${{ vars.VITE_PMTILES_URL }}
  VITE_OM_MAP_URL: ${{ vars.VITE_OM_MAP_URL }}
  VITE_MAPTILER_KEY: ${{ secrets.VITE_MAPTILER_KEY }}
  VITE_AWS_APIGATEWAY_KEY: ${{ secrets.VITE_AWS_APIGATEWAY_KEY }}
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Node セットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) 依存解決 & ビルド
      - name: Install deps & build
        working-directory: ./frontend
        run: |
          npm ci
          npx vite build

      # 4) AWS 資格情報を OIDC で取得
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          unset-current-credentials: true # 後続ジョブへの漏洩防止
          output-credentials: true

      # 5) S3 へ同期
      - name: Sync to S3
        run: |
          aws s3 sync ./frontend/dist s3://${{ env.BUCKET_NAME }} \
            --delete \
            --exclude 'public/*' \
            --exclude 'index.html' \
            --cache-control 'public,max-age=31536000,immutable' \

      # 6) index.html のみ no-cache で上書きアップロード
      - name: Upload index.html with no-cache
        run: |
          aws s3 cp ./frontend/dist/index.html s3://${{ env.BUCKET_NAME }}/index.html \
            --cache-control "no-cache, must-revalidate"

      # 7) CloudFrontのindex.htmlキャッシュを無効化
      - name: Invalidate CloudFront index.html
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"
